class AppStrings:
    id = "id"
    title = "title"
    name = "name"
    mobileNo = "mobile_no"
    email = "email"
    indianCitizen = "indian_citizen"
    gender = "gender"
    dateOfBirth = "date_of_birth"
    address = "address"
    state = "state"
    district = "district"
    country = "country"
    profilePic = "profile_pic"
    role = "role"
    createdAt = "created_at"
    updatedAt = "updated_at"